[package]
name = "app"
version = "1.0.0"
build = "build.rs"

[dependencies]
sgx-io-uring-ocalls = { path = "../deps/io-uring/ocalls" }
sgx_types = { path = "../deps/rust-sgx-sdk/sgx_types" }
sgx_urts = { path = "../deps/rust-sgx-sdk/sgx_urts" }

[workspace]
